spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/studyquerydsl
    username: studyquerydsl
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver